VuehappyJob20241219/octfair2

- test.txt
- 
- 
<br/>
- Closes #6 
<br/>
> test:#6 issue, pr test

- test.txt
> test commit nyr

- test.txt
- 
- 
<br/>
- Closes #9 
<br/>
> test#9 테스트9번

- test.txt
- 
- 
<br/>
- Closes #13 
<br/>
> feat: #13 test파일 추가

- test.txt
- 
- 
<br/>
- Closes #16 
<br/>
> feat#16 연습

- components.d.ts
- src/api/api.js
- src/components/page/Resume/ResumeEdit/ResumeWrite.vue
- src/components/page/Resume/ResumeMain/ResumeMain.vue
- src/router/index.js
- src/stores/userInfo.js
- src/views/Resume/Resume.vue
- vite.config.js
- 
- 
<br/>
- Closes #23 
<br/>
> 환경변수 및 url 경로수정

- components.d.ts
- src/components/layout/AddOnPack/LunchMenu.vue
- src/components/page/Resume/ResumeDetail/ResumeDetail.vue
- src/router/index.js
- 
- 
<br/>
- Closes #29
<br/>
> 배경화면 이미지 에러 수정

- .gitignore
- src/components/page/Resume/ResumeDetail/ResumeDetail.vue
- src/stores/resumeStore.js
- resumeDetail 나머지 구현
- pinia 사용
<br/>
- Closes #28 
<br/>
> feat/#28 resumeDetail, pinia 사용해서 구현

- src/components/page/Resume/ResumeDetail/ResumeDetail.vue
- 
- resumeCarrer 삭제
<br/>
- Closes #40 
<br/>
> resumeCarrer 삭제

- package-lock.json
- package.json
- src/App.vue
- src/common/nullCheck.js
- src/components/HelloWorld.vue
- src/components/common/ContextBox.vue
- src/components/common/Pagination.vue
- src/components/layout/AddOn.vue
- src/components/layout/AddOnPack/SnowSkin.vue
- src/components/page/Board/Notice/FirstNoticeModal.vue
- src/components/page/Board/Notice/FirstNoticeSearch.vue
- src/components/page/Board/Notice/NoticeDetail.vue
- src/components/page/Hire/HirePostMain.vue
- src/components/page/Jobs/Post/PostMain.vue
- src/components/page/Jobs/Post/PostSearch.vue
- src/components/page/Login/LoginMain.vue
- src/main.js
- src/router/index.js
- src/stores/modalState.js
- src/stores/userInfo.js
- src/views/Hire/HirePost.vue
- 기업 공고 관리 페이지 개발
<br/>
- Closes #32
<br/>
> feat/#32 기업 공고 관리 페이지

- components.d.ts
- src/components/layout/LeftManuBar.vue
- octfair2서버 특성상 /vue라는 실제경로와 proxy설정 /vue가 공존하여 충돌되는 문제
를 a href가 아니라 @click=router.go()로 바꾸어 수정
<br/>
- Closes #46 
<br/>
> fix:#46 좌상단 HappyJob로그 클릭시 메인화면으로 이동되게 Fix

- components.d.ts
- src/api/api.js
- src/api/approval/approvalListSearchApi.js
- src/components/page/Approval/ApprovalPostMain.vue
- src/components/page/Approval/ApprovalPostSearch.vue
- src/hook/approval/useApprovalListSearchQuery.js
- src/router/index.js
- src/views/Approval/ApprovalPost.vue
- 공고 심사 리스트 띄우기
- search 영역
<br/>
- Closes #45
<br/>
> feat/#45 공고 심사 리스트

- components.d.ts
- src/components/layout/LeftManuBar.vue
- 로그인 id 추가
- 
<br/>
- Closes #62 
<br/>
> feat:#62 reft bar에 로그인id 추가

- components.d.ts
- src/components/page/Company/CompanyDetail.vue
- src/router/index.js
- vite.config.js
- 기업 상세 조회 페이지 추가
- img 태그 관련 프록시 설정 추가
<br/>
- Closes #58 
<br/>
> 기업 상세 조회 페이지 구현

- package-lock.json
- package.json
- src/main.js
> #66 bootstrap 적용

- src/components/page/Hire/HirePostMain.vue
- src/components/page/ManageUser/Applicant/ApplicantMain.vue
- 공고관리 페이지 구현
- 버튼 수정
<br/>
- Closes #70 
<br/>
> 공고 관리 페이지 구현

- src/api/api.js
- src/api/jobs/postDetailDeleteApi.js
- src/api/jobs/postDetailSearchApi.js
- src/api/jobs/scrapUpdateApi.js
- src/api/notice/noticeDetailSearchApi.js
- src/components/page/Approval/ApprovalPostMain.vue
- src/components/page/Approval/ApprovalPostSearch.vue
- src/components/page/Company/CompanyDetail.vue
- src/components/page/Hire/HirePostMain.vue
- src/components/page/Jobs/Post/PostDetail.vue
- src/hook/jobs/usePostDetailDeleteMutation.js
- src/hook/jobs/usePostDetailSearchQuery.js
- src/hook/jobs/useScrapUpdateMutation.js
- src/router/index.js
- 페이지들끼리 연결 필요함
- 
<br/>
- Closes #55 
<br/>
> feat:#55 공고 보기 detail 페이지 구현

- components.d.ts
- src/api/api.js
- src/api/manageUser/applcantDetailSearchApi.js
- src/api/manageUser/applicantDetailUpdateApi.js
- src/api/manageUser/applicantListSearchApi.js
- src/api/manageUser/applicantPwResetApi.js
- src/components/page/ManageUser/Applicant/ApplicantMain.vue
- src/components/page/ManageUser/Applicant/ApplicantModal.vue
- src/components/page/ManageUser/Applicant/ApplicantSearch.vue
- src/hook/manageUser/useApplicantDetailSearchQuery.js
- src/hook/manageUser/useApplicantDetailUpdateMutation.js
- src/hook/manageUser/useApplicantListSearchQuery.js
- src/hook/manageUser/useApplicantPwResetMutation.js
- src/views/ManageUser/ManageApplicant.vue
- 구직자회원관리 페이지 tanstackQuery 적용
- 관련 메서드 모듈화 진행
<br/>
- Closes #76
<br/>
> 구직자회원관리 tanstack query 적용 및 관련 메서드 모듈화

- src/api/api.js
- src/api/manageUser/applicantDetailUpdateApi.js
- src/api/manageUser/bizDetailSearchApi.js
- src/api/manageUser/bizDetailUpdateApi.js
- src/api/manageUser/bizListSearchApi.js
- src/components/page/ManageUser/Biz/BizMain.vue
- src/components/page/ManageUser/Biz/BizModal.vue
- src/components/page/ManageUser/Biz/BizSearch.vue
- src/hook/manageUser/useBizDetailSearchQuery.js
- src/hook/manageUser/useBizDetailUpdateMutation.js
- src/hook/manageUser/useBizListSearchQuery.js
- src/views/ManageUser/ManageBiz.vue
- tanstack query 적용
- 메서드 모듈화
<br/>
- Closes #87 
<br/>
> 기업회원관리 tanstack query 적용 및 메서드 모듈화

- src/api/manageUser/applicantDetailUpdateApi.js
- src/api/manageUser/bizDetailUpdateApi.js
- src/components/page/ManageUser/Applicant/ApplicantMain.vue
- src/components/page/ManageUser/Biz/BizMain.vue
- src/hook/manageUser/useApplicantDetailUpdateMutation.js
- src/hook/manageUser/useApplicantListSearchQuery.js
- src/hook/manageUser/useBizDetailUpdateMutation.js
- src/hook/manageUser/useBizListSearchQuery.js
- vite.config.js
- update시 detailValue 인자값이 전달 안되는 걸 수정하였음
- modal 닫힐 때, refetch되게 수정하였음
<br/>
- Closes #89 
<br/>
> 개인회원관리, 기업회원관리 update 안되는 오류 해결

- src/components/page/Hire/HirePostEditor.vue
- src/components/page/Jobs/Post/PostDetail.vue
- src/router/index.js
- 공고보기에서 공고수정하기 연결
- 라우터 파일에 경로 추가
<br/>
- Closes #91 
<br/>
> 공고보기에서 공고수정하기 연결

- src/components/page/Jobs/Post/PostApplyModal.vue
- src/components/page/Jobs/Post/PostDetail.vue
- 입사 지원 modal 창 개발
- 공고 detail 파일 다운로드 추가
<br/>
- Closes #85
<br/>
> feat:#85 입사 지원 모달 개발 및 공고 detail 파일 다운로드 추가

- test.txt
> webhook test

- src/components/page/Hire/HirePostEditor.vue
- 공고 editor css 수정 (경력 여부 / 채용 절차)
<br/>
- Closes #103
<br/>
> feat/#103 공고 editor css 수정

- src/api/api.js
- src/components/layout/AddOnPack/LunchMenu.vue
- src/components/page/Apply/Resume/ResumeMain.vue
- src/components/page/Apply/Resume/ResumeStyle.css
- src/router/index.js
- src/views/DashBoard/DashBoard.vue
> 코드 복구, 및 겹치는 스타일클래스명 변경, 및 해피잡로고에 손모양포인터

- src/components/page/Jobs/Post/PostApplyModal.vue
- src/components/page/Jobs/Post/PostDetail.vue
- src/components/page/Jobs/Post/PostMain.vue
- src/components/page/Jobs/Post/PostSearch.vue
- src/components/page/Jobs/Scrap/ScrapMain.vue
- src/components/page/Jobs/Scrap/ScrapSearch.vue
- src/router/index.js
- src/views/Jobs/Scrap.vue
- 스크랩 페이지 개발
- 
<br/>
- Closes #114
<br/>
> feat:#114 스크랩 페이지

- src/components/page/Login/FindPwdModal.vue
- src/components/page/Login/SignUpModal.vue
- src/components/page/MyPage/MyPageMain.vue
- 마이페이지 회원정보 수정 수정함
- 
<br/>
<br/>
> feat/#82 마이페이지 회원정보 수정 수정함

- package-lock.json
- package.json
- src/components/page/Applicant/ApplicantBody.vue
- src/components/page/Hire/HirePostEditor.vue
- src/components/page/Hire/HirePostMain.vue
- button 강제 변경 
- 일부 코드 수정
<br/>
> button 강제 변경 및 일부 코드 수정

- src/components/page/ManageUser/Applicant/ApplicantModal.vue
- src/hook/manageUser/useApplicantDetailUpdateMutation.js
- src/hook/manageUser/useBizDetailUpdateMutation.js
- 개인회원관리, 기업회원관리 정보 수정시 에러 해결
- 
<br/>
- Closes #127 
<br/>
> 개인회원관리, 기업회원관리 정보 수정시 에러 해결

- src/components/page/Jobs/Post/PostDetail.vue
- detail 새로고침 안 되는 문제 수정
- 
<br/>
- Closes #121
<br/>
> feat:#114 공고 detail 새로고침 안 되는 문제 수정

- src/components/page/Jobs/Post/PostApplyModal.vue
- src/components/page/Jobs/Post/PostDetail.vue
- teleport 제거
- 
<br/>
- Closes #132
<br/>
> fix/#132 지원하기 modal 중복으로 뜨는 문제 수정

- src/components/page/Jobs/Post/PostDetail.vue
- 공고 Detail에서 페이지 이동 시 400 에러 뜨는 거 수정
<br/>
- Closes #134
<br/>
> fix/#134 공고 Detail에서 페이지 이동 시 400 에러 뜨는 거 수정

- src/components/page/Approval/ApprovalPostMain.vue
- src/components/page/Approval/ConfirmedPostMain.vue
- src/components/page/Jobs/Post/PostDetail.vue
- src/components/page/Jobs/Post/PostMain.vue
- src/components/page/Jobs/Scrap/ScrapMain.vue
- src/components/page/Jobs/Scrap/ScrapSearch.vue
- src/hook/approval/useApprovalListSearchQuery.js
- src/hook/jobs/usePostListSearchQuery.js
- src/hook/jobs/useScrapListSearchQuery.js
- src/router/index.js
- src/views/Jobs/Scrap.vue
- 공고 심사 후 해당 게시판으로 이동
- 페이지 이동 시 공고 심사, 공고 보기 리스트 등 새로 고침 되도록 수정
<br/>
- Closes #137
<br/>
> fix/#137 페이지 새로고침 문제 및 일부 수정

- src/components/page/Hire/HirePostEditor.vue
- src/views/Withdraw/Withdraw.vue
- route idx 변동되도 반응하게 수정
- 
<br/>
- Closes #146 
<br/>
> fix:#146 수정버튼 클릭시 route idx 변동에 반응하게 수정

- src/components/page/Hire/HirePostEditor.vue
- src/components/page/Jobs/Post/PostDetail.vue
- 공고 수정시 승인 여부 대기중으로 변경
- 승인된 공고는 수정 불가하게 변경
<br/>
- Closes #148
<br/>
> fix:#148 공고 수정시 승인 여부 대기중으로 변경, 승인된 공고는 수정 불가하게 변경

- src/components/page/Jobs/Post/PostDetail.vue
- src/hook/jobs/usePostDetailDeleteMutation.js
- delete mutation 부분 수정
<br/>
- Closes #150
<br/>
> fix/#150 공고 detail 삭제 안 되는 문제 수정

- src/components/page/Hire/HirePostEditor.vue
- 공고editor 유효성 검사 추가
- 
<br/>
- Closes #109 
<br/>
> 공고editor 유효성 검사 추가

- src/api/api.js
- src/api/company/companyDetailSearchApi.js
- src/components/page/Company/CompanyDetail.vue
- src/hook/company/useCompanyDetailSearchQuery.js
- tanstack query 적용
- 모듈화
<br/>
- Closes #156
<br/>
> 기업정보 보기 tanstack query 적용 및 모듈화

- src/components/page/Apply/History/HistoryMain.vue
- 개발자콘솔 경고 사항 처리: Pagination의 onClick함수를 화살표함수형으로 변경경
<br/>
<br/>
> Fix/#160 개발자콘솔 경고 사항 처리: Pagination의 onClick함수를 화살표함수형으로 변경

- src/api/api.js
- src/api/jobs/postDetailApplyApi.js
- src/api/jobs/postDetailDoScrapApi.js
- src/api/jobs/postDetailUnScrapApi.js
- src/api/jobs/postDetailUpdateStatusApi.js
- src/components/page/Hire/HirePostMain.vue
- src/components/page/Jobs/Post/PostApplyModal.vue
- src/components/page/Jobs/Post/PostDetail.vue
- src/components/page/Jobs/Scrap/ScrapMain.vue
- src/components/page/Jobs/Scrap/ScrapSearch.vue
- src/hook/jobs/usePostDetailApplyMutation.js
- src/hook/jobs/usePostDetailDoScrapMutation.js
- src/hook/jobs/usePostDetailUnScrapMutation.js
- src/hook/jobs/usePostUpdateStatusMutation.js
- 파일 다운로드 제외하고 tanstack 1차 적용 완료
<br/>
- Closes #139
<br/>
> feat:#139 tanstack query

- src/components/page/Qna/QnaMyDetailModal.vue
- src/components/page/Qna/QnaPasswordCheckModal.vue
- 파일 미리 보기 추가
- 새로고침 안 되는 문제 수정
- 비밀번호 입력해도 글 못 보는 문제 수정
- console.log 제거
<br/>
- Closes #164
<br/>
> fix/#164 qna 기능 수정

- src/components/page/Apply/Resume/InnerPage/CareerList.vue
- src/components/page/Apply/Resume/InnerPage/CertList.vue
- src/components/page/Apply/Resume/InnerPage/EduList.vue
- src/components/page/Apply/Resume/InnerPage/SkillList.vue
- feat:#160 이력서 잔데이터 남는 현상 제거
<br/>
<br/>
> Fix/#160 이력서 잔데이터 남는 현상 제거

- components.d.ts
- src/components/common/ContextBox.vue
- src/components/common/Pagination.vue
- src/components/layout/AddOn.vue
- src/components/layout/LeftManuBar.vue
- src/components/layout/LeftManuBar_test.vue
- src/components/page/Approval/ApprovalPostMain.vue
- src/components/page/Approval/ConfirmedPostMain.vue
- src/components/page/Hire/HirePostMain.vue
- src/components/page/Jobs/Post/PostMain.vue
- src/components/page/Jobs/Scrap/ScrapMain.vue
- src/views/DashBoard/DashBoard.vue
- css 적용
<br/>
- Closes #167
<br/>
> feat:#167 css 적용

- package.json
> package 수정

- components.d.ts
- src/components/page/Jobs/Post/PostApplyModal.vue
- src/components/page/Jobs/Post/PostDetail.vue
- 스크랩 페이지에서 지원 후 새로 고침 되도록 수정
<br/>
- Closes #175
<br/>
> feat:#175 스크랩 페이지 새로 고침

- src/components/page/Board/Notice/NoticeDetail.vue
- src/components/page/FAQ/FAQDetailModal.vue
> Feat/#61 css최종수정

- components.d.ts
- src/components/page/Board/Notice/NoticeDetail.vue
> feat/#61 css 최종본

- src/components/page/FAQ/FAQDetailModal.vue
- src/components/page/Qna/QnaDetailModal.vue
- src/components/page/Qna/QnaMain.vue
- src/components/page/Qna/QnaMyDetailModal.vue
- src/components/page/Qna/QnaPasswordCheckModal.vue
- 페이지 뒤로 가기 $router.go(-1)로 변경
- 관리자로 접속 시 글 안 보이는 문제 수정
- 새 글 작성 시 첨부 파일 보이도록 수정
- 새로 고침 수정
<br/>
- Closes #196
<br/>
> fix/#196 qna 수정
